### ISSUE TITLE
if is on form two stylemanagers, first is ignored

### ISSUE THREAD

**Issue by sgamescz** [N-a-r-w-i-n/MetroSet-UI#10]
if is on form used second stylenamager, fisrt is ignored and on all objects are set metrostylemanager2 instead metrostylemanager1

**Comment by N-a-r-w-i-n** [comment]
You don't have to add two style managers into one form for multiple controls all of them support custom colors that you can use them, or you create a custom theme and specify your desired colors to specific controls(but in that case colors will apply for every same control).
