### ISSUE TITLE
MetroSet_UI error when run (vb.net)

### ISSUE THREAD

**Issue by ItsMeMaiku** [N-a-r-w-i-n/MetroSet-UI#15]
It gives me an error like this

> Additional information: Could not load file or assembly 'MetroSet UI, Version=1.0.3.0, Culture=neutral, PublicKeyToken=null' or one of its dependencies. The system cannot find the file specified.

Even I follow the 2 methods it still gives me an error

**Comment by N-a-r-w-i-n** [comment]
provide the custom theme path in stylemanager component, you can download it an example of it [here ](https://github.com/N-a-r-w-i-n/MetroSet-UI/blob/master/MetroSet%20Theme.xml)
