### ISSUE TITLE
MetroSet_UI says install in nuget but say no reference when run

### ISSUE THREAD

**Issue by ItsMeMaiku** [N-a-r-w-i-n/MetroSet-UI#16]
MetroSet_UI  it says install in nuget but say no reference when running
it is saying no reference or wrong path direction

**Comment by N-a-r-w-i-n** [comment]
In upcoming days I try to update nuget version of this, stay tuned.

**Comment by N-a-r-w-i-n** [comment]
Nuget version just updated - tested - works successfully now.
