### ISSUE TITLE
buttons not change visual style after enabled=true/false

### ISSUE THREAD

**Issue by sgamescz** [N-a-r-w-i-n/MetroSet-UI#17]
if u change on button .enabled to true or false, button do not change own visual style to enabled / disabled design.
.refresh do not help.

**Comment by N-a-r-w-i-n** [comment]
I just checked it and it is not an issue but enabling and disabling controls don't show up in design time but in runtime.

**Comment by riskiadi** [comment]
yes so many bug on this lib
