### ISSUE TITLE
Base class 'Form' specified for class 'Form1' cannot be different from the base class 'MetroSetForm' of one of its other partial types.

### ISSUE THREAD

**Issue by rondellivey03** [N-a-r-w-i-n/MetroSet-UI#24]
I keep getting this error, it only does it whenever I put 
`Imports MetroSet_UI.Forms

public class Form1 : Inherits MetroSetForm

    Sub New()

    End Sub

End Class`

but if I replace it back to the default.
`Public Class Form1

End Class`
It works fine?

**Comment by ire4ever1190** [comment]
I had the same error and I solved it by inheriting the MetroSetForm in Form1.Designer.vb instead of Form1.vb

**Comment by rondellivey03** [comment]
I managed to fix this issue, thanks to ire4ever1190.

**Comment by Mahmoud20070** [comment]
> I had the same error and I solved it by inheriting the MetroSetForm in Form1.Designer.vb instead of Form1.vb

Thanks , working for me to

**Comment by quyzeq** [comment]
> I had the same error and I solved it by inheriting the MetroSetForm in Form1.Designer.vb instead of Form1.vb

how to inheriting the MetroSetForm in Form1.Designer.vb instead of Form1.vb. plz
idk :'(
