### ISSUE TITLE
Elements colors remain the same

### ISSUE THREAD

**Issue by Trickyyy** [N-a-r-w-i-n/MetroSet-UI#28]
I noticed 2 issues with the colors
1. Changing the color of any element doesn't matter if it's main or not will take a while, you must click on the other tab and click back in order to see the changes
2. After I completed the project and saved it, upon starting it again the colors were changed to the default ones, this was quite frustrating

Thanks for this wonderful framework, hoping for some assistance soon!

**Comment by P1X3LT0RCH** [comment]
Same issue at the moment.
So far much better framework in comparison to others, but it seems color changing is the main problem for all of them.
