### ISSUE TITLE
[REQUEST] Where is the orange and green theme

### ISSUE THREAD

**Issue by hAbd0u** [N-a-r-w-i-n/MetroSet-UI#32]
Hi,
Can you share the other themes you show in gif?

**Comment by N-a-r-w-i-n** [comment]
Here is the orange theme: [Here](https://github.com/N-a-r-w-i-n/MetroSet-UI/blob/master/MetroSet%20Theme.xml)

for the green one, you can just change the colors inside this XML file.

**Comment by N-a-r-w-i-n** [comment]
Please re-open the issue if you still had an issue with it.
