### ISSUE TITLE
DialogResult on MetroSetButton

### ISSUE THREAD

**Issue by cairoutm** [N-a-r-w-i-n/MetroSet-UI#35]
Hi;

Where can I find the DialogResult property for the MetroSetButton?

**Comment by N-a-r-w-i-n** [comment]
Hello
If you mean the DialogResult of MetroSetMessageBox which can be used inside other controls such as Button, etc...
Then Inside any control you can use :

var dialogResult = MetroSetMessageBox.Show(this /* The Form you're currently on */, "Content", "Title");

If you still have an issue on this please re-open this issue and let me know
