### ISSUE TITLE
MetroSet_UI Not Working

### ISSUE THREAD

**Issue by arifaarish** [N-a-r-w-i-n/MetroSet-UI#4]
Hi!,

First thank for this awesome project as per screenshot. Since not able to execute on my VS 2017 coz it is giving object reference not set to an object. 

request you to please help me out.

thanks,
![capture](https://user-images.githubusercontent.com/25843746/40433348-74ea802c-5ec9-11e8-8bfd-e80b9b9bc41a.JPG)

**Comment by N-a-r-w-i-n** [comment]
when you import the compiled MetroSet_UI.dll into your project and adding Style Manager to the forms make sure to provide the path for custom theme in Style Manager component then try to build your project.
