### ISSUE TITLE
Error using StyleManager

### ISSUE THREAD

**Issue by madijason** [N-a-r-w-i-n/MetroSet-UI#50]
![Capture d’écran 2022-01-29 222857](https://user-images.githubusercontent.com/66530748/151678104-ba813cf0-75fb-4b04-b297-b3f915810044.png)

**Comment by madijason** [comment]
It seems like if the error was due to .NET Framework 6

**Comment by mvpkenlin** [comment]
I have the same error too. But why the error message is "Microsoft.DotNet.DesignTools.Client.DesignToolsServerException: Invalid URL: The hostname could not be parsed"?

![image](https://user-images.githubusercontent.com/20411183/156329677-2b1bceed-6768-428b-8f17-89db18747b0d.png)
